---
# tasks file for apigee-opdk-start-components
- name: Stop all Apigee components on the node
  ignore_errors: yes
  shell: '{{ apigee_all }} stop'
  when: component_name == 'all' and opdk_version | version_compare('4.16.01', '>=') and opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'

- name: Stop a specific Apigee component on the node
  ignore_errors: yes
  shell: '{{ apigee_service }} {{ component_name }} stop'
  when: component_name != 'all' and opdk_version | version_compare('4.16.01', '>=') and opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'

- name: DEBUG_MODE - Stop all Apigee components on the node
  ignore_errors: yes
  shell: '{{ apigee_all }} stop'
  when: component_name == 'all' and opdk_version | version_compare('4.16.01', '>=') and opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'

- name: DEBUG_MODE - Stop a specific Apigee component on the node
  ignore_errors: yes
  shell: '{{ apigee_service }} {{ component_name }} stop'
  when: component_name != 'all' and opdk_version | version_compare('4.16.01', '>=') and opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'

